/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorDetails } from '../models/errorDetails.js';
import { LinkDescription } from '../models/linkDescription.js';

/**
 * Creates an instance of Subscription
 */
interface Subscription {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
  /** An array of additional details about the error. */
  details?: ErrorDetails[];
  /** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
  links?: LinkDescription[];
}

export class SubscriptionError extends ApiError<Subscription> {}
