/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A Resource representing a response of vaulted a ACH Debit Account. */
export interface ACHDebitResponse {
  /** The ach debit verification status. */
  verificationStatus?: string;
}

export const aCHDebitResponseSchema: Schema<ACHDebitResponse> = object({
  verificationStatus: ['verification_status', optional(string())],
});
