/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The auction information. */
export interface AuctionInformation {
  /** The name of the auction site. */
  auctionSite?: string;
  /** The auction site URL. */
  auctionItemSite?: string;
  /** The ID of the buyer who makes the purchase in the auction. This ID might be different from the payer ID provided for the payment. */
  auctionBuyerId?: string;
  /** The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates. */
  auctionClosingDate?: string;
}

export const auctionInformationSchema: Schema<AuctionInformation> = object({
  auctionSite: ['auction_site', optional(string())],
  auctionItemSite: ['auction_item_site', optional(string())],
  auctionBuyerId: ['auction_buyer_id', optional(string())],
  auctionClosingDate: ['auction_closing_date', optional(string())],
});
