/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AuthorizationIncompleteReason,
  authorizationIncompleteReasonSchema,
} from './authorizationIncompleteReason';

/** The details of the authorized payment status. */
export interface AuthorizationStatusDetails {
  /** The reason why the authorized status is `PENDING`. */
  reason?: AuthorizationIncompleteReason;
}

export const authorizationStatusDetailsSchema: Schema<AuthorizationStatusDetails> = object(
  { reason: ['reason', optional(authorizationIncompleteReasonSchema)] }
);
