/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AvsCode
 */
export enum AvsCode {
  AvsA = 'A',
  AvsB = 'B',
  AvsC = 'C',
  AvsD = 'D',
  AvsE = 'E',
  AvsF = 'F',
  AvsG = 'G',
  AvsI = 'I',
  AvsM = 'M',
  AvsN = 'N',
  AvsP = 'P',
  AvsR = 'R',
  AvsS = 'S',
  AvsU = 'U',
  AvsW = 'W',
  AvsX = 'X',
  AvsY = 'Y',
  AvsZ = 'Z',
  AvsNull = 'Null',
  Avs0 = '0',
  Avs1 = '1',
  Avs2 = '2',
  Avs3 = '3',
  Avs4 = '4',
}

/**
 * Schema for AvsCode
 */
export const avsCodeSchema: Schema<AvsCode> = stringEnum(AvsCode, true);
