/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ACHDebitResponse, aCHDebitResponseSchema } from './aCHDebitResponse';
import {
  SEPADebitResponse,
  sEPADebitResponseSchema,
} from './sEPADebitResponse';

/** Full representation of a Bank Payment Token. */
export interface BankPaymentToken {
  /** A Resource representing a response of vaulted a ACH Debit Account. */
  achDebit?: ACHDebitResponse;
  sepaDebit?: SEPADebitResponse;
}

export const bankPaymentTokenSchema: Schema<BankPaymentToken> = object({
  achDebit: ['ach_debit', optional(lazy(() => aCHDebitResponseSchema))],
  sepaDebit: ['sepa_debit', optional(lazy(() => sEPADebitResponseSchema))],
});
