/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallbackEvents
 */
export enum CallbackEvents {
  ShippingAddress = 'SHIPPING_ADDRESS',
  ShippingOptions = 'SHIPPING_OPTIONS',
}

/**
 * Schema for CallbackEvents
 */
export const callbackEventsSchema: Schema<CallbackEvents> = stringEnum(
  CallbackEvents,
  true
);
