/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CaptureType
 */
export enum CaptureType {
  OutstandingBalance = 'OUTSTANDING_BALANCE',
}

/**
 * Schema for CaptureType
 */
export const captureTypeSchema: Schema<CaptureType> = stringEnum(
  CaptureType,
  true
);
