/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { CaptureType, captureTypeSchema } from './captureType.js';
import { Money, moneySchema } from './money.js';

/** The charge amount from the subscriber. */
export interface CaptureSubscriptionRequest {
  /** The reason or note for the subscription charge. */
  note: string;
  /** The type of capture. */
  captureType: CaptureType;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  amount: Money;
}

export const captureSubscriptionRequestSchema: Schema<CaptureSubscriptionRequest> = object(
  {
    note: ['note', string()],
    captureType: ['capture_type', captureTypeSchema],
    amount: ['amount', lazy(() => moneySchema)],
  }
);
