/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CaptureStatus
 */
export enum CaptureStatus {
  Completed = 'COMPLETED',
  Declined = 'DECLINED',
  PartiallyRefunded = 'PARTIALLY_REFUNDED',
  Pending = 'PENDING',
  Refunded = 'REFUNDED',
  Failed = 'FAILED',
}

/**
 * Schema for CaptureStatus
 */
export const captureStatusSchema: Schema<CaptureStatus> = stringEnum(
  CaptureStatus,
  true
);
