/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardVerificationMethod
 */
export enum CardVerificationMethod {
  SCAALWAYS = 'SCA_ALWAYS',
  SCAWHENREQUIRED = 'SCA_WHEN_REQUIRED',
  Enum3DSECURE = '3D_SECURE',
  AVSCVV = 'AVS_CVV',
}

/**
 * Schema for CardVerificationMethod
 */
export const cardVerificationMethodSchema: Schema<CardVerificationMethod> = stringEnum(
  CardVerificationMethod,
  true
);
