/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string, unknown } from '../schema.js';
import { CardBrand, cardBrandSchema } from './cardBrand.js';
import {
  CardVerificationProcessorResponse,
  cardVerificationProcessorResponseSchema,
} from './cardVerificationProcessorResponse.js';
import { Money, moneySchema } from './money.js';

/** Card Verification details including the authorization details and 3D SECURE details. */
export interface CardVerificationDetails {
  /** DEPRECATED. This field is DEPRECATED. Please find the network transaction id data in the 'id' field under the 'network_transaction_reference' object instead of the 'verification' object. */
  networkTransactionId?: string;
  /** DEPRECATED. This field is DEPRECATED. Please find the date data in the 'date' field under the 'network_transaction_reference' object instead of the 'verification' object. */
  date?: string;
  /** DEPRECATED. This field is DEPRECATED. Please find the network data in the 'network' field under the 'network_transaction_reference' object instead of the 'verification' object. */
  network?: CardBrand;
  /** DEPRECATED. This field is DEPRECATED. Please find the time data in the 'time' field under the 'network_transaction_reference' object instead of the 'verification' object. */
  time?: string;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  amount?: Money;
  /** The processor response information for payment requests, such as direct credit card transactions. */
  processorResponse?: CardVerificationProcessorResponse;
  /** DEPRECATED. This field is DEPRECATED. Please find the 3D secure authentication data in the 'three_d_secure' object under the 'authentication_result' object instead of the 'verification' object. */
  threeDSecure?: unknown;
}

export const cardVerificationDetailsSchema: Schema<CardVerificationDetails> = object(
  {
    networkTransactionId: ['network_transaction_id', optional(string())],
    date: ['date', optional(string())],
    network: ['network', optional(cardBrandSchema)],
    time: ['time', optional(string())],
    amount: ['amount', optional(lazy(() => moneySchema))],
    processorResponse: [
      'processor_response',
      optional(lazy(() => cardVerificationProcessorResponseSchema)),
    ],
    threeDSecure: ['three_d_secure', optional(unknown())],
  }
);
