/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ThreeDSecureAuthenticationResponse,
  threeDSecureAuthenticationResponseSchema,
} from './threeDSecureAuthenticationResponse';

/** Results of Authentication such as 3D Secure. */
export interface CardAuthenticationResponse {
  /** Results of 3D Secure Authentication. */
  threeDSecure?: ThreeDSecureAuthenticationResponse;
}

export const cardAuthenticationResponseSchema: Schema<CardAuthenticationResponse> = object(
  {
    threeDSecure: [
      'three_d_secure',
      optional(lazy(() => threeDSecureAuthenticationResponseSchema)),
    ],
  }
);
