/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** A checkout option as a name-and-value pair. */
export interface CheckoutOption {
  /** The checkout option name, such as `color` or `texture`. */
  checkoutOptionName?: string;
  /** The checkout option value. For example, the checkout option `color` might be `blue` or `red` while the checkout option `texture` might be `smooth` or `rippled`. */
  checkoutOptionValue?: string;
}

export const checkoutOptionSchema: Schema<CheckoutOption> = object({
  checkoutOptionName: ['checkout_option_name', optional(string())],
  checkoutOptionValue: ['checkout_option_value', optional(string())],
});
