/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** This object defines a customer in your system. Use it to manage customer profiles, save payment methods and contact details. */
export interface CustomerResponse {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /** Merchants and partners may already have a data-store where their customer information is persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer. */
  merchantCustomerId?: string;
}

export const customerResponseSchema: Schema<CustomerResponse> = object({
  id: ['id', optional(string())],
  merchantCustomerId: ['merchant_customer_id', optional(string())],
});
