/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';
import {
  FrequencyIntervalUnit,
  frequencyIntervalUnitSchema,
} from './frequencyIntervalUnit.js';

/** The frequency of the terms reset cycle. */
export interface CycleFrequency {
  /** The interval unit at which the the usage limits will be reset. */
  intervalUnit: FrequencyIntervalUnit;
  /** The interval count at which the terms will be reset, this is ignored if the unit is LIFETIME. */
  intervalCount?: number;
}

export const cycleFrequencySchema: Schema<CycleFrequency> = object({
  intervalUnit: ['interval_unit', frequencyIntervalUnitSchema],
  intervalCount: ['interval_count', optional(number())],
});
