/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DisbursementMode
 */
export enum DisbursementMode {
  INSTANT = 'INSTANT',
  DELAYED = 'DELAYED',
}

/**
 * Schema for DisbursementMode
 */
export const disbursementModeSchema: Schema<DisbursementMode> = stringEnum(
  DisbursementMode,
  true
);
