/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ExperienceStatus
 */
export enum ExperienceStatus {
  NotStarted = 'NOT_STARTED',
  InProgress = 'IN_PROGRESS',
  Canceled = 'CANCELED',
  Approved = 'APPROVED',
}

/**
 * Schema for ExperienceStatus
 */
export const experienceStatusSchema: Schema<ExperienceStatus> = stringEnum(
  ExperienceStatus,
  true
);
