/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FrequencyIntervalUnit
 */
export enum FrequencyIntervalUnit {
  Day = 'DAY',
  Week = 'WEEK',
  Month = 'MONTH',
  Year = 'YEAR',
  Lifetime = 'LIFETIME',
}

/**
 * Schema for FrequencyIntervalUnit
 */
export const frequencyIntervalUnitSchema: Schema<FrequencyIntervalUnit> = stringEnum(
  FrequencyIntervalUnit,
  true
);
