/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FullfillmentType
 */
export enum FullfillmentType {
  Shipping = 'SHIPPING',
  PickupInPerson = 'PICKUP_IN_PERSON',
  PickupInStore = 'PICKUP_IN_STORE',
  PickupFromPerson = 'PICKUP_FROM_PERSON',
}

/**
 * Schema for FullfillmentType
 */
export const fullfillmentTypeSchema: Schema<FullfillmentType> = stringEnum(
  FullfillmentType,
  true
);
