/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GooglePayAuthenticationMethod
 */
export enum GooglePayAuthenticationMethod {
  PANONLY = 'PAN_ONLY',
  CRYPTOGRAM3DS = 'CRYPTOGRAM_3DS',
}

/**
 * Schema for GooglePayAuthenticationMethod
 */
export const googlePayAuthenticationMethodSchema: Schema<GooglePayAuthenticationMethod> = stringEnum(
  GooglePayAuthenticationMethod,
  true
);
