/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GooglePayAuthenticationMethod
 */
export enum GooglePayAuthenticationMethod {
  PanOnly = 'PAN_ONLY',
  Cryptogram3Ds = 'CRYPTOGRAM_3DS',
}

/**
 * Schema for GooglePayAuthenticationMethod
 */
export const googlePayAuthenticationMethodSchema: Schema<GooglePayAuthenticationMethod> = stringEnum(
  GooglePayAuthenticationMethod,
  true
);
