/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Money, moneySchema } from './money.js';

/** The incentive details. */
export interface IncentiveDetails {
  /** The type of incentive, such as a special offer or coupon. */
  incentiveType?: string;
  /** The code that identifies an incentive, such as a coupon. */
  incentiveCode?: string;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  incentiveAmount?: Money;
  /** The incentive program code that identifies a merchant loyalty or incentive program. */
  incentiveProgramCode?: string;
}

export const incentiveDetailsSchema: Schema<IncentiveDetails> = object({
  incentiveType: ['incentive_type', optional(string())],
  incentiveCode: ['incentive_code', optional(string())],
  incentiveAmount: ['incentive_amount', optional(lazy(() => moneySchema))],
  incentiveProgramCode: ['incentive_program_code', optional(string())],
});
