/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemCategory
 */
export enum ItemCategory {
  DIGITALGOODS = 'DIGITAL_GOODS',
  PHYSICALGOODS = 'PHYSICAL_GOODS',
  DONATION = 'DONATION',
}

/**
 * Schema for ItemCategory
 */
export const itemCategorySchema: Schema<ItemCategory> = stringEnum(
  ItemCategory,
  true
);
