/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemCategory
 */
export enum ItemCategory {
  DigitalGoods = 'DIGITAL_GOODS',
  PhysicalGoods = 'PHYSICAL_GOODS',
  Donation = 'DONATION',
}

/**
 * Schema for ItemCategory
 */
export const itemCategorySchema: Schema<ItemCategory> = stringEnum(
  ItemCategory,
  true
);
