/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Money, moneySchema } from './money.js';

export interface LastPaymentDetails {
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  amount?: Money;
  /** The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates. */
  time?: string;
}

export const lastPaymentDetailsSchema: Schema<LastPaymentDetails> = object({
  amount: ['amount', optional(lazy(() => moneySchema))],
  time: ['time', optional(string())],
});
