/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LinkHTTPMethod
 */
export enum LinkHTTPMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  CONNECT = 'CONNECT',
  OPTIONS = 'OPTIONS',
  PATCH = 'PATCH',
}

/**
 * Schema for LinkHTTPMethod
 */
export const linkHTTPMethodSchema: Schema<LinkHTTPMethod> = stringEnum(
  LinkHTTPMethod,
  true
);
