/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The merchant preferences for a subscription. */
export interface MerchantPreferences {
  /** The URL where the customer is redirected after the customer approves the payment. */
  returnUrl?: string;
  /** The URL where the customer is redirected after the customer cancels the payment. */
  cancelUrl?: string;
}

export const merchantPreferencesSchema: Schema<MerchantPreferences> = object({
  returnUrl: ['return_url', optional(string())],
  cancelUrl: ['cancel_url', optional(string())],
});
