/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  MobileReturnFlow,
  mobileReturnFlowSchema,
} from './mobileReturnFlow.js';

/** Buyer's mobile web browser context to app switch to the PayPal consumer app. */
export interface MobileWebContext {
  /** Merchant preference on how the buyer can navigate back to merchant website post approving the transaction on the PayPal App. */
  returnFlow?: MobileReturnFlow;
  /** User agent from the request originating from the buyer's device. This will be used to identify the buyer's operating system and browser versions. NOTE: Merchants must not alter or modify the buyer's device user agent. */
  buyerUserAgent?: string;
}

export const mobileWebContextSchema: Schema<MobileWebContext> = object({
  returnFlow: ['return_flow', optional(mobileReturnFlowSchema)],
  buyerUserAgent: ['buyer_user_agent', optional(string())],
});
