/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for MobileReturnFlow
 */
export enum MobileReturnFlow {
  Auto = 'AUTO',
  Manual = 'MANUAL',
}

/**
 * Schema for MobileReturnFlow
 */
export const mobileReturnFlowSchema: Schema<MobileReturnFlow> = stringEnum(
  MobileReturnFlow,
  true
);
