/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Money, moneySchema } from './money';

/** The one-time charge info at the time of checkout. */
export interface OneTimeCharge {
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  setupFee?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  shippingAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  taxes?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  productPrice?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  subtotal?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  totalAmount: Money;
}

export const oneTimeChargeSchema: Schema<OneTimeCharge> = object({
  setupFee: ['setup_fee', optional(lazy(() => moneySchema))],
  shippingAmount: ['shipping_amount', optional(lazy(() => moneySchema))],
  taxes: ['taxes', optional(lazy(() => moneySchema))],
  productPrice: ['product_price', optional(lazy(() => moneySchema))],
  subtotal: ['subtotal', optional(lazy(() => moneySchema))],
  totalAmount: ['total_amount', lazy(() => moneySchema)],
});
