/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Money, moneySchema } from './money.js';

/** The one-time charge info at the time of checkout. */
export interface OneTimeCharge {
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  setupFee?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  shippingAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  taxes?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  productPrice?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  subtotal?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  totalAmount: Money;
}

export const oneTimeChargeSchema: Schema<OneTimeCharge> = lazy(() =>
  object({
    setupFee: ['setup_fee', optional(moneySchema)],
    shippingAmount: ['shipping_amount', optional(moneySchema)],
    taxes: ['taxes', optional(moneySchema)],
    productPrice: ['product_price', optional(moneySchema)],
    subtotal: ['subtotal', optional(moneySchema)],
    totalAmount: ['total_amount', moneySchema],
  })
);
