/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderApplicationContextLandingPage
 */
export enum OrderApplicationContextLandingPage {
  Login = 'LOGIN',
  Billing = 'BILLING',
  NoPreference = 'NO_PREFERENCE',
}

/**
 * Schema for OrderApplicationContextLandingPage
 */
export const orderApplicationContextLandingPageSchema: Schema<OrderApplicationContextLandingPage> = stringEnum(
  OrderApplicationContextLandingPage,
  true
);
