/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderStatus
 */
export enum OrderStatus {
  Created = 'CREATED',
  Saved = 'SAVED',
  Approved = 'APPROVED',
  Voided = 'VOIDED',
  Completed = 'COMPLETED',
  PayerActionRequired = 'PAYER_ACTION_REQUIRED',
}

/**
 * Schema for OrderStatus
 */
export const orderStatusSchema: Schema<OrderStatus> = stringEnum(
  OrderStatus,
  true
);
