/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OsType
 */
export enum OsType {
  Android = 'ANDROID',
  Ios = 'IOS',
  Other = 'OTHER',
}

/**
 * Schema for OsType
 */
export const osTypeSchema: Schema<OsType> = stringEnum(OsType, true);
