/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PAResStatus
 */
export enum PAResStatus {
  Y = 'Y',
  N = 'N',
  U = 'U',
  A = 'A',
  C = 'C',
  R = 'R',
  D = 'D',
  I = 'I',
}

/**
 * Schema for PAResStatus
 */
export const pAResStatusSchema: Schema<PAResStatus> = stringEnum(
  PAResStatus,
  true
);
