/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaResStatus
 */
export enum PaResStatus {
  Y = 'Y',
  N = 'N',
  U = 'U',
  A = 'A',
  C = 'C',
  R = 'R',
  D = 'D',
  I = 'I',
}

/**
 * Schema for PaResStatus
 */
export const paResStatusSchema: Schema<PaResStatus> = stringEnum(
  PaResStatus,
  true
);
