/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Profile information of the sender or receiver. */
export interface ParticipantMetadata {
  /** An Internet Protocol address (IP address). This address assigns a numerical label to each device that is connected to a computer network through the Internet Protocol. Supports IPv4 and IPv6 addresses. */
  ipAddress?: string;
}

export const participantMetadataSchema: Schema<ParticipantMetadata> = object({
  ipAddress: ['ip_address', optional(string())],
});
