/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PatchOp
 */
export enum PatchOp {
  Add = 'add',
  Remove = 'remove',
  Replace = 'replace',
  Move = 'move',
  Copy = 'copy',
  Test = 'test',
}

/**
 * Schema for PatchOp
 */
export const patchOpSchema: Schema<PatchOp> = stringEnum(PatchOp, true);
