/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  PayeePaymentMethodPreference,
  payeePaymentMethodPreferenceSchema,
} from './payeePaymentMethodPreference.js';

/** The customer and merchant payment preferences. */
export interface PaymentMethod {
  /** The merchant-preferred payment methods. */
  payeePreferred?: PayeePaymentMethodPreference;
}

export const paymentMethodSchema: Schema<PaymentMethod> = object({
  payeePreferred: [
    'payee_preferred',
    optional(payeePaymentMethodPreferenceSchema),
  ],
});
