/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentInitiator
 */
export enum PaymentInitiator {
  Customer = 'CUSTOMER',
  Merchant = 'MERCHANT',
}

/**
 * Schema for PaymentInitiator
 */
export const paymentInitiatorSchema: Schema<PaymentInitiator> = stringEnum(
  PaymentInitiator,
  true
);
