/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentTokenStatus
 */
export enum PaymentTokenStatus {
  Created = 'CREATED',
  PayerActionRequired = 'PAYER_ACTION_REQUIRED',
  Approved = 'APPROVED',
  Vaulted = 'VAULTED',
  Tokenized = 'TOKENIZED',
}

/**
 * Schema for PaymentTokenStatus
 */
export const paymentTokenStatusSchema: Schema<PaymentTokenStatus> = stringEnum(
  PaymentTokenStatus,
  true
);
