/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayPalWalletVaultStatus
 */
export enum PayPalWalletVaultStatus {
  VAULTED = 'VAULTED',
  CREATED = 'CREATED',
  APPROVED = 'APPROVED',
}

/**
 * Schema for PayPalWalletVaultStatus
 */
export const payPalWalletVaultStatusSchema: Schema<PayPalWalletVaultStatus> = stringEnum(
  PayPalWalletVaultStatus,
  true
);
