/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaypalWalletAccountVerificationStatus
 */
export enum PaypalWalletAccountVerificationStatus {
  Verified = 'VERIFIED',
  Unverified = 'UNVERIFIED',
}

/**
 * Schema for PaypalWalletAccountVerificationStatus
 */
export const paypalWalletAccountVerificationStatusSchema: Schema<PaypalWalletAccountVerificationStatus> = stringEnum(
  PaypalWalletAccountVerificationStatus,
  true
);
