/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaypalPaymentTokenUsagePattern
 */
export enum PaypalPaymentTokenUsagePattern {
  IMMEDIATE = 'IMMEDIATE',
  DEFERRED = 'DEFERRED',
  RECURRINGPREPAID = 'RECURRING_PREPAID',
  RECURRINGPOSTPAID = 'RECURRING_POSTPAID',
  THRESHOLDPREPAID = 'THRESHOLD_PREPAID',
  THRESHOLDPOSTPAID = 'THRESHOLD_POSTPAID',
}

/**
 * Schema for PaypalPaymentTokenUsagePattern
 */
export const paypalPaymentTokenUsagePatternSchema: Schema<PaypalPaymentTokenUsagePattern> = stringEnum(
  PaypalPaymentTokenUsagePattern,
  true
);
