/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Money, moneySchema } from './money.js';

/** The pricing tier details. */
export interface PricingTier {
  /** The starting quantity for the tier. */
  startingQuantity: string;
  /** The ending quantity for the tier. Optional for the last tier. */
  endingQuantity?: string;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  amount: Money;
}

export const pricingTierSchema: Schema<PricingTier> = object({
  startingQuantity: ['starting_quantity', string()],
  endingQuantity: ['ending_quantity', optional(string())],
  amount: ['amount', lazy(() => moneySchema)],
});
