/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Money, moneySchema } from './money';
import { PricingModel, pricingModelSchema } from './pricingModel';

/** The pricing scheme details. */
export interface PricingScheme {
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  price?: Money;
  /** The pricing model for the billing cycle. */
  pricingModel: PricingModel;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  reloadThresholdAmount?: Money;
}

export const pricingSchemeSchema: Schema<PricingScheme> = object({
  price: ['price', optional(lazy(() => moneySchema))],
  pricingModel: ['pricing_model', pricingModelSchema],
  reloadThresholdAmount: [
    'reload_threshold_amount',
    optional(lazy(() => moneySchema)),
  ],
});
