/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PricingModel
 */
export enum PricingModel {
  Fixed = 'FIXED',
  Variable = 'VARIABLE',
  AutoReload = 'AUTO_RELOAD',
}

/**
 * Schema for PricingModel
 */
export const pricingModelSchema: Schema<PricingModel> = stringEnum(
  PricingModel,
  true
);
