/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProcessingInstruction
 */
export enum ProcessingInstruction {
  OrderCompleteOnPaymentApproval = 'ORDER_COMPLETE_ON_PAYMENT_APPROVAL',
}

/**
 * Schema for ProcessingInstruction
 */
export const processingInstructionSchema: Schema<ProcessingInstruction> = stringEnum(
  ProcessingInstruction,
  true
);
