/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProcessingInstruction
 */
export enum ProcessingInstruction {
  /** API Caller expects the Order to be auto completed (i.e. for PayPal to authorize or capture depending on the intent) on completion of payer approval. This option is not relevant for payment_source that typically do not require a payer approval or interaction. */
  OrderCompleteOnPaymentApproval = 'ORDER_COMPLETE_ON_PAYMENT_APPROVAL',
  /** The API caller intends to authorize v2/checkout/orders/{id}/authorize or capture v2/checkout/orders/{id}/capture after the payer approves the order. */
  NoInstruction = 'NO_INSTRUCTION',
}

/**
 * Schema for ProcessingInstruction
 */
export const processingInstructionSchema: Schema<ProcessingInstruction> = stringEnum(
  ProcessingInstruction,
  true
);
