/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReasonCode
 */
export enum ReasonCode {
  PaymentDenied = 'PAYMENT_DENIED',
  InternalServerError = 'INTERNAL_SERVER_ERROR',
  PayeeAccountRestricted = 'PAYEE_ACCOUNT_RESTRICTED',
  PayerAccountRestricted = 'PAYER_ACCOUNT_RESTRICTED',
  PayerCannotPay = 'PAYER_CANNOT_PAY',
  SendingLimitExceeded = 'SENDING_LIMIT_EXCEEDED',
  TransactionReceivingLimitExceeded = 'TRANSACTION_RECEIVING_LIMIT_EXCEEDED',
  CurrencyMismatch = 'CURRENCY_MISMATCH',
}

/**
 * Schema for ReasonCode
 */
export const reasonCodeSchema: Schema<ReasonCode> = stringEnum(
  ReasonCode,
  true
);
