/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RefundStatus
 */
export enum RefundStatus {
  Cancelled = 'CANCELLED',
  Failed = 'FAILED',
  Pending = 'PENDING',
  Completed = 'COMPLETED',
}

/**
 * Schema for RefundStatus
 */
export const refundStatusSchema: Schema<RefundStatus> = stringEnum(
  RefundStatus,
  true
);
