/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReturnFlow
 */
export enum ReturnFlow {
  Auto = 'AUTO',
  Manual = 'MANUAL',
}

/**
 * Schema for ReturnFlow
 */
export const returnFlowSchema: Schema<ReturnFlow> = stringEnum(
  ReturnFlow,
  true
);
