/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ParticipantMetadata,
  participantMetadataSchema,
} from './participantMetadata';

/** Additional information necessary to evaluate the risk profile of a transaction. */
export interface RiskSupplementaryData {
  /** Profile information of the sender or receiver. */
  customer?: ParticipantMetadata;
}

export const riskSupplementaryDataSchema: Schema<RiskSupplementaryData> = object(
  { customer: ['customer', optional(lazy(() => participantMetadataSchema))] }
);
