/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SetupFeeFailureAction
 */
export enum SetupFeeFailureAction {
  Continue = 'CONTINUE',
  Cancel = 'CANCEL',
}

/**
 * Schema for SetupFeeFailureAction
 */
export const setupFeeFailureActionSchema: Schema<SetupFeeFailureAction> = stringEnum(
  SetupFeeFailureAction,
  true
);
