/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaypalPaymentToken,
  paypalPaymentTokenSchema,
} from './paypalPaymentToken.js';
import {
  SetupTokenResponseCard,
  setupTokenResponseCardSchema,
} from './setupTokenResponseCard.js';
import {
  VenmoPaymentToken,
  venmoPaymentTokenSchema,
} from './venmoPaymentToken.js';

/** The setup payment method details. */
export interface SetupTokenResponsePaymentSource {
  card?: SetupTokenResponseCard;
  /** Full representation of a PayPal Payment Token. */
  paypal?: PaypalPaymentToken;
  /** Full representation of a Venmo Payment Token. */
  venmo?: VenmoPaymentToken;
}

export const setupTokenResponsePaymentSourceSchema: Schema<SetupTokenResponsePaymentSource> = object(
  {
    card: ['card', optional(lazy(() => setupTokenResponseCardSchema))],
    paypal: ['paypal', optional(lazy(() => paypalPaymentTokenSchema))],
    venmo: ['venmo', optional(lazy(() => venmoPaymentTokenSchema))],
  }
);
