/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The name of the party. */
export interface ShippingName {
  /** When the party is a person, the party's full name. */
  fullName?: string;
}

export const shippingNameSchema: Schema<ShippingName> = object({
  fullName: ['full_name', optional(string())],
});
