/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StandardEntryClassCode
 */
export enum StandardEntryClassCode {
  Tel = 'TEL',
  Web = 'WEB',
  Ccd = 'CCD',
  Ppd = 'PPD',
}

/**
 * Schema for StandardEntryClassCode
 */
export const standardEntryClassCodeSchema: Schema<StandardEntryClassCode> = stringEnum(
  StandardEntryClassCode,
  true
);
