/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StoredPaymentSourcePaymentType
 */
export enum StoredPaymentSourcePaymentType {
  OneTime = 'ONE_TIME',
  Recurring = 'RECURRING',
  Unscheduled = 'UNSCHEDULED',
}

/**
 * Schema for StoredPaymentSourcePaymentType
 */
export const storedPaymentSourcePaymentTypeSchema: Schema<StoredPaymentSourcePaymentType> = stringEnum(
  StoredPaymentSourcePaymentType,
  true
);
