/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Money, moneySchema } from './money.js';

/** The breakdown details for the amount. Includes the gross, tax, fee, and shipping amounts. */
export interface SubscriptionAmountWithBreakdown {
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  grossAmount: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  totalItemAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  feeAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  shippingAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  taxAmount?: Money;
  /** The currency and amount for a financial transaction, such as a balance or payment due. */
  netAmount?: Money;
}

export const subscriptionAmountWithBreakdownSchema: Schema<SubscriptionAmountWithBreakdown> = object(
  {
    grossAmount: ['gross_amount', lazy(() => moneySchema)],
    totalItemAmount: ['total_item_amount', optional(lazy(() => moneySchema))],
    feeAmount: ['fee_amount', optional(lazy(() => moneySchema))],
    shippingAmount: ['shipping_amount', optional(lazy(() => moneySchema))],
    taxAmount: ['tax_amount', optional(lazy(() => moneySchema))],
    netAmount: ['net_amount', optional(lazy(() => moneySchema))],
  }
);
