/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Name, nameSchema } from './name.js';
import { ShippingDetails, shippingDetailsSchema } from './shippingDetails.js';
import {
  SubscriptionPaymentSourceResponse,
  subscriptionPaymentSourceResponseSchema,
} from './subscriptionPaymentSourceResponse.js';

/** The subscriber response information. */
export interface Subscriber {
  /** The name of the party. */
  name?: Name;
  /** The shipping details. */
  shippingAddress?: ShippingDetails;
  /** The payment source used to fund the payment. */
  paymentSource?: SubscriptionPaymentSourceResponse;
}

export const subscriberSchema: Schema<Subscriber> = object({
  name: ['name', optional(lazy(() => nameSchema))],
  shippingAddress: [
    'shipping_address',
    optional(lazy(() => shippingDetailsSchema)),
  ],
  paymentSource: [
    'payment_source',
    optional(lazy(() => subscriptionPaymentSourceResponseSchema)),
  ],
});
