/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { LinkDescription, linkDescriptionSchema } from './linkDescription.js';
import { Subscription, subscriptionSchema } from './subscription.js';

/** The list of subscriptions. */
export interface SubscriptionCollection {
  /** An array of subscriptions. */
  subscriptions?: Subscription[];
  /** An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
  links?: LinkDescription[];
}

export const subscriptionCollectionSchema: Schema<SubscriptionCollection> = object(
  {
    subscriptions: [
      'subscriptions',
      optional(array(lazy(() => subscriptionSchema))),
    ],
    links: ['links', optional(array(lazy(() => linkDescriptionSchema)))],
  }
);
