/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SubscriptionPlanStatus
 */
export enum SubscriptionPlanStatus {
  Created = 'CREATED',
  Inactive = 'INACTIVE',
  Active = 'ACTIVE',
}

/**
 * Schema for SubscriptionPlanStatus
 */
export const subscriptionPlanStatusSchema: Schema<SubscriptionPlanStatus> = stringEnum(
  SubscriptionPlanStatus,
  true
);
