/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CardResponseWithBillingAddress,
  cardResponseWithBillingAddressSchema,
} from './cardResponseWithBillingAddress.js';

/** The payment source used to fund the payment. */
export interface SubscriptionPaymentSourceResponse {
  /** The payment card used to fund the payment. Card can be a credit or debit card. */
  card?: CardResponseWithBillingAddress;
}

export const subscriptionPaymentSourceResponseSchema: Schema<SubscriptionPaymentSourceResponse> = object(
  { card: ['card', optional(lazy(() => cardResponseWithBillingAddressSchema))] }
);
