/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** The suspend subscription request details. */
export interface SuspendSubscription {
  /** The reason for suspension of the Subscription. */
  reason: string;
}

export const suspendSubscriptionSchema: Schema<SuspendSubscription> = object({
  reason: ['reason', string()],
});
