/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

/** The tax details. */
export interface TaxesOverride {
  /** The percentage, as a fixed-point, signed decimal number. For example, define a 19.99% interest rate as `19.99`. */
  percentage?: string;
  /** Indicates whether the tax was already included in the billing amount. */
  inclusive?: boolean;
}

export const taxesOverrideSchema: Schema<TaxesOverride> = object({
  percentage: ['percentage', optional(string())],
  inclusive: ['inclusive', optional(boolean())],
});
