/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxIdType
 */
export enum TaxIdType {
  BrCpf = 'BR_CPF',
  BrCnpj = 'BR_CNPJ',
}

/**
 * Schema for TaxIdType
 */
export const taxIdTypeSchema: Schema<TaxIdType> = stringEnum(TaxIdType, true);
