/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TenureType
 */
export enum TenureType {
  Regular = 'REGULAR',
  Trial = 'TRIAL',
}

/**
 * Schema for TenureType
 */
export const tenureTypeSchema: Schema<TenureType> = stringEnum(
  TenureType,
  true
);
