/**
 * Paypal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenRequestType
 */
export enum TokenRequestType {
  SETUPTOKEN = 'SETUP_TOKEN',
  BILLINGAGREEMENT = 'BILLING_AGREEMENT',
}

/**
 * Schema for TokenRequestType
 */
export const tokenRequestTypeSchema: Schema<TokenRequestType> = stringEnum(
  TokenRequestType,
  true
);
