/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  AuctionInformation,
  auctionInformationSchema,
} from './auctionInformation.js';
import { CartInformation, cartInformationSchema } from './cartInformation.js';
import {
  IncentiveInformation,
  incentiveInformationSchema,
} from './incentiveInformation.js';
import {
  PayerInformation,
  payerInformationSchema,
} from './payerInformation.js';
import {
  ShippingInformation,
  shippingInformationSchema,
} from './shippingInformation.js';
import {
  StoreInformation,
  storeInformationSchema,
} from './storeInformation.js';
import {
  TransactionInformation,
  transactionInformationSchema,
} from './transactionInformation.js';

/** The transaction details. */
export interface TransactionDetails {
  /** The transaction information. */
  transactionInfo?: TransactionInformation;
  /** The payer information. */
  payerInfo?: PayerInformation;
  /** The shipping information. */
  shippingInfo?: ShippingInformation;
  /** The cart information. */
  cartInfo?: CartInformation;
  /** The store information. */
  storeInfo?: StoreInformation;
  /** The auction information. */
  auctionInfo?: AuctionInformation;
  /** The incentive details. */
  incentiveInfo?: IncentiveInformation;
}

export const transactionDetailsSchema: Schema<TransactionDetails> = object({
  transactionInfo: [
    'transaction_info',
    optional(lazy(() => transactionInformationSchema)),
  ],
  payerInfo: ['payer_info', optional(lazy(() => payerInformationSchema))],
  shippingInfo: [
    'shipping_info',
    optional(lazy(() => shippingInformationSchema)),
  ],
  cartInfo: ['cart_info', optional(lazy(() => cartInformationSchema))],
  storeInfo: ['store_info', optional(lazy(() => storeInformationSchema))],
  auctionInfo: ['auction_info', optional(lazy(() => auctionInformationSchema))],
  incentiveInfo: [
    'incentive_info',
    optional(lazy(() => incentiveInformationSchema)),
  ],
});
