/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UpcType
 */
export enum UpcType {
  UpcA = 'UPC-A',
  UpcB = 'UPC-B',
  UpcC = 'UPC-C',
  UpcD = 'UPC-D',
  UpcE = 'UPC-E',
  Upc2 = 'UPC-2',
  Upc5 = 'UPC-5',
}

/**
 * Schema for UpcType
 */
export const upcTypeSchema: Schema<UpcType> = stringEnum(UpcType, true);
