/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UPCType
 */
export enum UPCType {
  UPCA = 'UPC-A',
  UPCB = 'UPC-B',
  UPCC = 'UPC-C',
  UPCD = 'UPC-D',
  UPCE = 'UPC-E',
  UPC2 = 'UPC-2',
  UPC5 = 'UPC-5',
}

/**
 * Schema for UPCType
 */
export const uPCTypeSchema: Schema<UPCType> = stringEnum(UPCType, true);
