/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import {
  UpdatePricingScheme,
  updatePricingSchemeSchema,
} from './updatePricingScheme.js';

/** The update pricing scheme request details. */
export interface UpdatePricingSchemesRequest {
  /** An array of pricing schemes. */
  pricingSchemes: UpdatePricingScheme[];
}

export const updatePricingSchemesRequestSchema: Schema<UpdatePricingSchemesRequest> = object(
  {
    pricingSchemes: [
      'pricing_schemes',
      array(lazy(() => updatePricingSchemeSchema)),
    ],
  }
);
