/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VaultInstructionAction
 */
export enum VaultInstructionAction {
  OnCreatePaymentTokens = 'ON_CREATE_PAYMENT_TOKENS',
  OnPayerApproval = 'ON_PAYER_APPROVAL',
}

/**
 * Schema for VaultInstructionAction
 */
export const vaultInstructionActionSchema: Schema<VaultInstructionAction> = stringEnum(
  VaultInstructionAction,
  true
);
