/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  ApplePayRequestCard,
  applePayRequestCardSchema,
} from './applePayRequestCard.js';

/** A resource representing a request to vault Apple Pay. */
export interface VaultApplePayRequest {
  /** Encrypted Apple Pay token, containing card information. This token would be base64 encoded. */
  token?: string;
  /** The payment card to be used to fund a payment. Can be a credit or debit card. */
  card?: ApplePayRequestCard;
}

export const vaultApplePayRequestSchema: Schema<VaultApplePayRequest> = object({
  token: ['token', optional(string())],
  card: ['card', optional(lazy(() => applePayRequestCardSchema))],
});
