/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VaultTokenRequestType
 */
export enum VaultTokenRequestType {
  SetupToken = 'SETUP_TOKEN',
}

/**
 * Schema for VaultTokenRequestType
 */
export const vaultTokenRequestTypeSchema: Schema<VaultTokenRequestType> = stringEnum(
  VaultTokenRequestType,
  true
);
