/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VenmoWalletExperienceContextShippingPreference
 */
export enum VenmoWalletExperienceContextShippingPreference {
  GetFromFile = 'GET_FROM_FILE',
  NoShipping = 'NO_SHIPPING',
  SetProvidedAddress = 'SET_PROVIDED_ADDRESS',
}

/**
 * Schema for VenmoWalletExperienceContextShippingPreference
 */
export const venmoWalletExperienceContextShippingPreferenceSchema: Schema<VenmoWalletExperienceContextShippingPreference> = stringEnum(
  VenmoWalletExperienceContextShippingPreference,
  true
);
