/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  VenmoVaultResponse,
  venmoVaultResponseSchema,
} from './venmoVaultResponse.js';

/** Additional attributes associated with the use of a Venmo Wallet. */
export interface VenmoWalletAttributesResponse {
  /** The details about a saved venmo payment source. */
  vault?: VenmoVaultResponse;
}

export const venmoWalletAttributesResponseSchema: Schema<VenmoWalletAttributesResponse> = object(
  { vault: ['vault', optional(lazy(() => venmoVaultResponseSchema))] }
);
