/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VenmoWalletExperienceContextUserAction
 */
export enum VenmoWalletExperienceContextUserAction {
  Continue = 'CONTINUE',
  PayNow = 'PAY_NOW',
}

/**
 * Schema for VenmoWalletExperienceContextUserAction
 */
export const venmoWalletExperienceContextUserActionSchema: Schema<VenmoWalletExperienceContextUserAction> = stringEnum(
  VenmoWalletExperienceContextUserAction,
  true
);
