/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  CustomerInformation,
  customerInformationSchema,
} from './customerInformation.js';
import { LinkDescription, linkDescriptionSchema } from './linkDescription.js';
import {
  VenmoVaultResponseStatus,
  venmoVaultResponseStatusSchema,
} from './venmoVaultResponseStatus.js';

/** The details about a saved venmo payment source. */
export interface VenmoVaultResponse {
  /** The PayPal-generated ID for the saved payment source. */
  id?: string;
  /** The vault status. */
  status?: VenmoVaultResponseStatus;
  /** An array of request-related HATEOAS links. */
  links?: LinkDescription[];
  /** This object represents a merchant’s customer, allowing them to store contact details, and track all payments associated with the same customer. */
  customer?: CustomerInformation;
}

export const venmoVaultResponseSchema: Schema<VenmoVaultResponse> = object({
  id: ['id', optional(string())],
  status: ['status', optional(venmoVaultResponseStatusSchema)],
  links: ['links', optional(array(lazy(() => linkDescriptionSchema)))],
  customer: ['customer', optional(lazy(() => customerInformationSchema))],
});
